global:
  scrape_interval: 15s


  external_labels:
    monitor: 'broker-project'

scrape_configs:
  - job_name: monitoring
    static_configs:
      - targets:
          - go-main-service-with-metrics-and-grafana12:5050
          - go-main-service-with-metrics-and-grafana12:5051

  - job_name: prometheus
    static_configs:
      - targets: [ 'localhost:9090' ]



