global:
  scrape_interval: 15s


  external_labels:
    monitor: 'broker-project'

scrape_configs:
  - job_name: monitoring
    metrics_path: /metrics
    static_configs:
      - targets:
          - go-main-service-with-metrics-and-grafana60:5051

  - job_name: prometheus
    static_configs:
      - targets: [ 'localhost:9090']




