apiVersion: v1
kind: Pod
metadata:
  name: broker-pod
  labels:
    app: broker
    type: server
spec:
  containers:
    - name: broker-pod-container
      image: broker-master_go-main-service-with-metrics-and-grafana27
      imagePullPolicy: Never
