apiVersion: v1
kind: Service
metadata:
  name: broker-service
  labels:
    name: broker-service
    app: broker
spec:
  type: NodePort
  selector:
    name: broker-pod
    app: broker
  ports:
    - port: 90
      targetPort: 90
      nodePort: 30006
