apiVersion: v1
kind: Pod
metadata:
  name: broker-pod
  labels:
    name: broker-pod
    app: broker
spec:
  containers:
    - name: broker-pod-container
      image: broker-master_go-main-service-with-metrics-and-grafana27
      imagePullPolicy: Never
      ports:
        - containerPort: 90
