version: "3.7"

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus/

    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

    ports:
      - 9090:9090
    depends_on:
      - go-main-service-with-metrics-and-grafana69

  go-main-service-with-metrics-and-grafana69:
    build: .

    ports:
      - 5051:5051
      - 5050:5050

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000

  postgresql1:
#    restart: always
    image: postgres:latest
    container_name: postgres
    user: 1000:1000

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/mnt

    volumes:
      - PGDATA:/var/lib/postgresql/data

    ports:
      - 5432:5432

volumes:
  PGDATA:
    driver: local
